version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PASSWORD=postgres
    volumes:
      - ./src:/app
    ports:
      - "5000:80"

  db:
    image: postgres
    environment:
      - POSTGRES_USER=cluesolver
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
